gold_link_reseau:
    resource: "@GoldLinkReseauBundle/Resources/config/routing.yml"
    prefix:   /membres


gold_link_lien:
    resource: "@GoldLinkLienBundle/Resources/config/routing.yml"
    prefix:   /membres

hwi_facebook_login:
    pattern: /connexion/login_facebook

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connexion

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /connexion

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix:   /connexion

hwi_github_login:
    pattern: /connexion/check-github

hwi_foursquare_login:
    pattern: /connexion/foursquare

hwi_linkedin_login:
    pattern: /connexion/linkedin

hwi_twitter_login:
    pattern: /connexion/twitter

hwi_dropbox_login:
    pattern: /connexion/dropbox

gold_link_user:
    resource: "@GoldLinkUserBundle/Resources/config/routing.yml"
    prefix:   /membres

gold_link_accueil:
    resource: "@GoldLinkAccueilBundle/Resources/config/routing.yml"
    prefix:   /

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /inscription

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /mise-a-jour

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
login_admin:
    pattern: /admin/login
    defaults: {_controller: GoldLinkUserBundle:Admin:login}
logout_admin:
    pattern: /admin/logout
