security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_SONATA_ADMIN, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
        SONATA:
            - ROLE_SONATA_PAGE_ADMIN_PAGE_EDIT


    providers:

        fos_userbunble:
            id: fos_user.user_provider.username
        main:
            id: fos_user.user_provider.username
        admin_provider:
            id: fos_user.user_manager

        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        admin:
            pattern: ^/admin(.*)
            form-login:
                provider: admin_provider
                login_path: /admin/login
                use_forward: false
                check_path: /admin/login
                failure_path: null
                default_target_path: sonata_admin_redirect
            logout:
                path: /admin/logout
                target: /admin/login
            anonymous: true
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        connexion:
            pattern: ^/connexion$
            security: false

        secure_area:
            pattern: ^/connexion

            oauth:
                failure_path: /connexion
                login_path: /connexion
                check_path: /connexion
                provider: fos_userbundle
                resource_owners:
                    github:           "/connexion/check-github"
                    facebook:         "/connexion/login_facebook"
                oauth_user_provider:
                    service: hwi_oauth.user.provider.fosub_bridge

            anonymous:    true
            logout:
                path:           /connexion/logout
                target:         /connexion/ #where to go after logout
        main:
            pattern: ^/
            anonymous: true
            provider: main
            form_login:
                always_use_default_target_path: true
                default_target_path: acces_membres
                login_path:  hwi_oauth_connect
                check_path: fos_user_security_check
            logout:
                path: fos_user_security_logout
                target: /
            remember_me:
                key: %secret%
    #...

    access_control:
        #....
        - { path: ^/secure_area/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/secure_area/connect, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/secure_area, roles: ROLE_USER }
        - { path: ^/membres, roles: ROLE_USER }

        #.... Administration

        - { path: ^/admin/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/logout$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/login-check$, role: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: ^/admin, role: [ROLE_ADMIN, ROLE_SONATA_ADMIN] }
        - { path: ^/.*, role: IS_AUTHENTICATED_ANONYMOUSLY }



        
