<?php

namespace GoldLink\LienBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * cliquerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class cliquerRepository extends EntityRepository{

    public function getCliqueOf($userId , $lienId){
       return $this->findBy(['userClique' => $userId , 'lienClique' => $lienId]);
    }

    public function cliqueExist($userId , $lienId){
        $clique = $this->getCliqueOf($userId,$lienId);
        return is_array($clique) && !empty($clique);
    }
}
