<?php

namespace GoldLink\LienBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * membresRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class membresRepository extends EntityRepository
{
    public function findGroupeMembres($userId){
        $requete = '
            SELECT M,G.id groupeId ,G.nomDuGroupe nomDuGroupe,U
            FROM GoldLink\LienBundle\Entity\membres M
            join M.grouperAdhesion G
            join M.userAdhesion U
            where U.id =';
        $requete .= $userId;
        $requete = $this->getEntityManager()->createQuery($requete)->getResult();
        return $requete;
    }
}
