<?php

namespace GoldLink\LienBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * notationsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class notationsRepository extends EntityRepository
{
    public function getNotationUser($Iduser){
        $query = $this->getEntityManager()->createQuery("SELECT notation FROM GoldLinkLienBundle:notations notation WHERE notation.userNote = :user")
            ->setParameter('user',$Iduser);
        return $query->getResult();

    }
}
