<?php

namespace GoldLink\LienBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * publicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class publicationRepository extends EntityRepository
{
    public function getNewsPubs($debut=0,$fin=5){
        $query = $this->getEntityManager()
            ->createQuery('SELECT pub From GoldLinkLienBundle:Publication pub ORDER By pub.id DESC')
            ->setFirstResult($debut)
            ->setMaxResults($fin);
        ;
        return $query->getResult();
    }
}
