<?php

namespace GoldLink\LienBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * VisibiliteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VisibiliteRepository extends EntityRepository
{
}
