parameters:
#    gold_link_reseau.example.class: GoldLink\ReseauBundle\Example

services:
#    gold_link_reseau.example:
#        class: %gold_link_reseau.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
