<?php

namespace GoldLink\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DemandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DemandeRepository extends EntityRepository
{
    public function getDemandeOfUser($userId){
        $requete = '
            SELECT D,E,G FROM GoldLinkUserBundle:Demande D
            JOIN D.emetteur E JOIN D.groupe G WHERE G.administrateur = :userId
        ';
        $requete = $this->getEntityManager()->createQuery($requete)->setParameter('userId',$userId)->getResult();
        return $requete;
    }

    public function demandeExiste($userId , $groupeId , $emetteurId ){
        $requete = 'SELECT D FROM GoldLinkUserBundle:Demande D
            JOIN D.emetteur E JOIN D.groupe G WHERE G.administrateur = :userId
            and E.id = :emetteurId and G.id = :groupeId
        ';
        $requete = $this->getEntityManager()->createQuery($requete)
            ->setParameter('userId',$userId)
            ->setParameter('emetteurId',$emetteurId)
            ->setParameter('groupeId',$groupeId)
            ->getResult();
        return count($requete) > 0;
    }

    public function deleteDemande($groupeId , $emetteurId ){
        $requete = '
            DELETE FROM GoldLinkUserBundle:Demande D
            WHERE D.emetteur = :emetteurId and D.groupe = :groupeId
        ';
        $requete = $this->getEntityManager()->createQuery($requete)
            ->setParameter('emetteurId',$emetteurId)
            ->setParameter('groupeId',$groupeId)
            ->getResult();
        return $requete;
    }
}
