<?php

namespace GoldLink\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GroupeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupeRepository extends EntityRepository
{
    public function getbyNom($nom){
        return $this->findOneByNom($nom);
    }

    public function findGroupes($nom){
        $requete = $this->createQueryBuilder('g')->where('g.nomDuGroupe LIKE :nomDuGroupe')->setParameter('nomDuGroupe','%'.$nom.'%');
        $requete = $requete->getQuery();
        $requete=$requete->getResult();
        return $requete;
    }

    public function findToutGroupe($userId) {
        $requete = $this->getEntityManager()->createQuery('
            SELECT g groupe FROM GoldLinkUserBundle:Groupe g WHERE
            g.administrateur = '.$userId.'
        ')->getResult();

        return $requete;
    }

    public function rechercherGroupe($groupe,$userId){
        $requete = 'SELECT G FROM GoldLinkUserBundle:Groupe G WHERE G.administrateur <> :userId';
        $requete.=' AND G.nomDuGroupe LIKE :groupe';
        $requete = $this->getEntityManager()->createQuery($requete);
        $requete->setParameter('userId', $userId)
            ->setParameter('groupe','%'.$groupe.'%');
        return $requete->getResult();
    }

    public function deleteMembres($id){
        $requete = 'DELETE FROM GoldLinkLienBundle:membres M WHERE M.grouperAdhesion = :id';
        $requete = $this
            ->getEntityManager()
            ->createQuery($requete)
            ->setParameter('id' , $id)
            ->getResult();
        return $requete;
    }

    public function deletePublicationGroupe($id){
        $requete = 'DELETE FROM GoldLinkLienBundle:PublicationGroupe PG WHERE PG.groupe = :id';
        $requete = $this
            ->getEntityManager()
            ->createQuery($requete)
            ->setParameter('id' , $id)
            ->getResult();
        return $requete;
    }
    public function deleteDemande($id){
        $requete = 'DELETE FROM GoldLinkUserBundle:Demande D WHERE D.groupe = :id';
        $requete = $this
            ->getEntityManager()
            ->createQuery($requete)
            ->setParameter('id' , $id)
            ->getResult();
        return $requete;
    }
    public function deleteCascade($id){

        $this->deleteMembres($id);
        $this->deletePublicationGroupe($id);
        $this->deleteDemande($id);
    }

}
