<?php

namespace GoldLink\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
   public function getNewsUsers($debut=0,$fin=5){
        $query = $this->getEntityManager()
            ->createQuery('SELECT user From GoldLinkUserBundle:User user ORDER By user.id DESC ')
            ->setFirstResult($debut)
            ->setMaxResults($fin);
            ;
        return $query->getResult();
    }
}
